# workflow name
name: Deploy Project
# an event that trigger workflow
# use bracket to specify multiple events
on: [push, workflow_dispatch]
# jobs is what process should this workflow do
jobs: 
  # the job name
  test-and-build:
    # specified the runners machine or the environtment will use to run a job
    runs-on: ubuntu-latest
    steps:
    # Github actions required to download our codes/project from the repository
    - name: Pull/download the codes
      # uses is a key to using github actions
      # for more info about checkout actions, please visit this page https://github.com/marketplace/actions/checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn  --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=false -DdeployAtEnd=false -Drevision=$VERSION clean compile
    - name: Test
      run: mvn  --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=false -DdeployAtEnd=false -Drevision=$VERSION clean verify
    - name: Package
      run: mvn  --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=false -DdeployAtEnd=false -Drevision=$VERSION clean package -DskipTests=true
  # if second job presented in the workflow, it will be run parallel with the first job
  deploy:
    # by using needs, we can specify which job should be completed first before this job run
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Pull/download the codes
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Deploy
      run: mvn  --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=false -DdeployAtEnd=false -Drevision=$VERSION clean package -DskipTests=true