name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        # This step outputs the GitHub context information
        # Use special syntax to get the context ${{ }}
        # See github context documentation: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
        # Alos toJson is an expression function that available on Github Expressions
        # see Github Expressions: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions
        run: |
          echo "${{ toJson(github) }}"