name: Pull Request Demo
on:
  pull_request:
    # can also triggered by [opened, synchronize, reopened]
    # Each event can have none or multiple activities types
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print message
        run: echo "This is a pull request demo"